### ISSUE TITLE
Timedelay in Update and Delete Command

### ISSUE THREAD

**Issue by accerpcom** [aymendhaya/ra-data-firebase-client#17]
Hello, 

I love your boilerplate and using it for a project but there is a critical problem ( at least from user experience point of view ). After you update or delete the record it takes few seconds to reach out to this line. I tried debugging but could not found much.  

/src/lib/RestProvider.js 
181: console.log('UPDATE/CREATE');  

Have you seen this issue before ?

**Comment by aymendhaya** [comment]
Hi, this delay can be set on react-admin level, you should disable undoable feature
`<Edit undoable={false} ...`
