### ISSUE TITLE
Can I have custom identifiers/primary keys for my resources?

### ISSUE THREAD

**Issue by aelhirach** [aymendhaya/ra-data-firebase-client#19]
ra-data-firebase-client requires that each resource has an id field to identify it. my data uses a different name for the primary key, can i map that name to id in your dataProvider.

**Comment by herrmannplatz** [comment]
Ran into the same issue. How did you solved it @aelhirach ?

I just adopted the code, that it returns the data with an id derived from the key. Would be nice to have an option for that? Should i make a PR ?
