### ISSUE TITLE
AuthProvider does not work with Firestore

### ISSUE THREAD

**Issue by seaver-choy** [aymendhaya/ra-data-firebase-client#2]
I have added a new user with the credentials from auth, however, there is sign_in_error that comes out.

Is it right for me to say that it does not work for firestore as of the moment? Thank you!

**Comment by aymendhaya** [comment]
Hi @seaver-choy , please feel free to check #1 if it match your auth requirement, and concerning firestore unfortunatly we still does not suport it yet. Thanks

**Comment by seaver-choy** [comment]
Oh. So maybe the api states sign_in_error is 
because the api is checking Firebase Realtime Database for the user, but I have stored the user in Firestore which causes the error. Will try to edit the code to work with Firestore. Thank you!

**Comment by rafalzawadzki** [comment]
Hey, for anyone in need, I created a Firestore version here: https://github.com/rafalzawadzki/ra-data-firestore-client

**Comment by naiduasn** [comment]
@rafalzawadzki i am facing one issue with ra-data-firestore-client. But i was not able to create issue in your project.

It happens for Show Method. I was able to pull the data into list and display via DataGrid. But when i click on any item inside Grid, it will not take me inside details.

So i have manually navigated by adding '/show' to the url, which results in below error

`Warning: Missing translation for key: "Id not found"`

Any idea why this is happenig?
