### ISSUE TITLE
Show Child listing

### ISSUE THREAD

**Issue by jayna06** [aymendhaya/ra-data-firebase-client#4]
Hello
i want to show listing inside of main route..i am not finding a way to do so using firebase client or may be react admin ..
Like.. users - specific user -> Feedbacks listing
 I m not able to list feedbacks listing on edit user .. feedbacks is not stored separate so i cant  use referenceinput or reference fields

**Comment by aymendhaya** [comment]
Hi @jayna06 , 
Actually this is not an issue related to `ra-data-firebase-client`neither `react-admin`. To satisfy your need. In `react-admin`documentation related to Inputs, you can find the answer of your demand. which is using the full path as a source string for your Input/Field(a.e source="item.subitem". 
See more at https://github.com/marmelab/react-admin/blob/master/docs/Inputs.md#input-components.

**Comment by LAITRUNGMINHDUC** [comment]
@aymendhaya  Hello guys, I think I have a similar issue to this. 

In Firebase Database, I have:
```
{
  "accounts": {
    "MEh2UB6Yd8d0kU": [
      {        
        "email": "abc@abc.com", 
        "access_token": "Lorem", 
        "refresh_token": "Lorem", 
        "access_token_expired": "Lorem",
        "refresh_token_expired": "Lorem"
      }
    ],
    L1PHeyBd3M5L2": [
      {        
        "email": "def-abc@abc.com", 
        "access_token": "Lorem", 
        "refresh_token": "Lorem", 
        "access_token_expired": "Lorem",
        "refresh_token_expired": "Lorem"
      }    
  }
}
```

And in App.js, I write:

```
const trackedResources = [
  { name: 'accounts', isPublic: false}, 
  { name: 'users', isPublic: false}
];

const App = () => (
  <Admin history={history} authProvider={AuthProvider(authConfig)} dataProvider={dataProvider}>
    <Resource name="accounts" list={AccountList} edit={AccountEdit} create={AccountCreate} />
  </Admin>
);
```
How could I list the array of 'MEh2UB6Yd8d0kU' (UserID) and 'L1PHeyBd3M5L2' (UserID) to Resource? Thanks a lot.

**Comment by aymendhaya** [comment]
hi @LAITRUNGMINHDUC , 
It is probably because ` isPublic` has been set to false, try to follow this example: https://github.com/aymendhaya/ra-data-firebase-client/blob/master/src/demo/App.js
**Good luck**

**Comment by LAITRUNGMINHDUC** [comment]
@aymendhaya: Hi, thanks for it, I have figured out the issue (Firebase Security rules) and fix it well. I think it would be better if you provide the "Warning" notification (similar to Login Page) for any cannot Read/Write issue.

Besides that, about the Realtime of Firebase, I cannot use it. After data changed, it doesn't update. I have to click F5, and the Refresh button doesn't work. If you haven't provided that, please consider this.

Also, there is a small thing that should be fixed (because it's small, I don't make a pull request):
```
In line 18 of file AuthProvider.js, of commit **7c42a164f0adc56e844322257d498c66610891ea** , 
you can navigate here: https://github.com/aymendhaya/ra-data-firebase-client/blob/7c42a164f0adc56e844322257d498c66610891ea/src/lib/AuthProvider.js

It should be: const firebaseToken = **await** auth.user.getIdToken(); to get the token and save it to localStorage
```
Thanks a lot, your work is great.
