### ISSUE TITLE
Feature Request: Search and Filters

### ISSUE THREAD

**Issue by alfonsodev** [aymendhaya/ra-data-firebase-client#5]
Are there any plans to support react-admin filters ? 

https://marmelab.com/react-admin/Tutorial.html#adding-search-and-filters-to-the-list

**Comment by aymendhaya** [comment]
Hi @alfonsodev , thank you for your suggestion and sorry of late reply

Updates supporting filtring & sorting will be published `January 13th`. I will close this issue when updates are published on the next version. 

Have a good hack

**Comment by jayna06** [comment]
Is filtering and sorting supported now???

**Comment by VincentCtr** [comment]
Hello @aymendhaya do you have any news about the release of this feature ? 

Thank you again for this amazing work.

**Comment by VincentCtr** [comment]
For those who are looking for this feature:

I added the search feature to the methods on https://github.com/welovedevs/ra-data-firebase-client

**Comment by jayna06** [comment]
Hello @VincentCtr yes its working but you need to find with full value .. if name then you need to give full name to find.. 
I think you should use indexof instead of startwith.. so it works correctly...??
if (propsToFilterToString.indexOf('' + filterValue)>-1)

**Comment by VincentCtr** [comment]
Hello @jayna06 ,

Thanks for the feedback, I updated the PR using includes.

I also removed the npm package as one of my coworker told me that it was not a good practice to add a new package to the registry for a PR.

Use this command to add the package:
yarn add https://github.com/welovedevs/ra-data-firebase-client.git#master

**Comment by jayna06** [comment]
@VincentCtr great .. Thanks for the update and making this filter too 👍

**Comment by brownieboy** [comment]
@VincentCtr,

Your PR worked for me first time!  I was able to filter my DataGrid on a ReferencField in a way that the main package did not allow, and I didn't have to change any code. 👍 

We need this merged into the main ra-data-firebase-client asap.

**Comment by aymendhaya** [comment]
Hi, please check v3 release and demo at [https://aymendhaya.github.io/ra-data-firebase-client](https://aymendhaya.github.io/ra-data-firebase-client)
