### ISSUE TITLE
Automatically refresh token

### ISSUE THREAD

**Issue by afilp** [aymendhaya/ra-data-firebase-client#6]
Hello,

Firebase token seems to expire every 1 hour.

This causes problems when there are actions to be made, is there a way to automatically refresh the token in the background before the hour expires? Or some other solution?

We want the logged-in user to remain logged-in until they choose to logout.

Thanks.

P.S. Similar discussion here (for Android apps though):
https://stackoverflow.com/questions/38350843/how-to-handle-custom-firebase-token-expiry-in-firebase-3-x-x
P.S. Using react-admin v2.6.1

**Comment by aymendhaya** [comment]
Hi, authProvider on v3 has been moved to a seperate project 
[https://github.com/aymendhaya/ra-auth-firebase-client](https://github.com/aymendhaya/ra-auth-firebase-client.) 
Please feel free to open the same issue on the other repo so we can track and work on it.

Thank you for your remarks
