### ISSUE TITLE
Can't upload image

### ISSUE THREAD

**Issue by johhansantana** [aymendhaya/ra-data-firebase-client#9]
I'm using the [forked firestore version](https://github.com/rafalzawadzki/ra-data-firestore-client) of this and when I try to use the image component to upload an image I get the following error:

```
DocumentReference.set() called with invalid data. Unsupported field value: a custom File object (found in field pictures.rawFile)
```

This is my component:
```
<ImageInput source="pictures" label="Slide picture" accept="image/*">
  <ImageField source="src" title="title" />
</ImageInput>
```

**Comment by johhansantana** [comment]
after debugging for a bit, it only happens when you try to create a new entry that has that component. If you create the entry without the component and then add the image in the `edit` view, it will upload successfully.

**Comment by rafalzawadzki** [comment]
Hi @johhansantana, you can track the progress on this issue [here](https://github.com/rafalzawadzki/ra-data-firestore-client/issues/6) :)

**Comment by aymendhaya** [comment]
Hi, please check the v3 release
